# Docker Compose V2 format (no version needed)
services:
  schema-service:
    build: .
    environment:
      - SCHEMA_VERSION=${SCHEMA_VERSION:-latest}
      - CLIENT_LANGUAGES=${CLIENT_LANGUAGES:-node,python,typescript}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO=${GITHUB_REPO:-leadvantageadmin/hailmary-schema}
    volumes:
      - .:/app
      - ~/.gitconfig:/root/.gitconfig:ro
    networks:
      - hailmary-network

  schema-api:
    build: .
    ports:
      - "3001:3001"
    environment:
      - SCHEMA_VERSION=${SCHEMA_VERSION:-latest}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    command: ["node", "scripts/schema-api.js"]
    volumes:
      - ./versions:/app/versions
      - ./scripts:/app/scripts
    networks:
      - hailmary-network

networks:
  hailmary-network:
    driver: bridge
